# Generated by Django 5.2.3 on 2025-06-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(default='nothing', max_length=1000)),
                ('name', models.CharField(default='nothing', max_length=100)),
                ('email', models.EmailField(default='nothing', max_length=100)),
                ('password', models.CharField(default='nothing', max_length=100)),
                ('address', models.CharField(default='nothing', max_length=100)),
                ('city', models.CharField(default='nothing', max_length=100)),
                ('state', models.CharField(default='nothing', max_length=100)),
                ('zipcode', models.CharField(default='nothing', max_length=100)),
                ('totalprice', models.CharField(blank=True, default='nothing', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
