# Generated by Django 5.2.3 on 2025-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orders_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Items',
            field=models.CharField(default='nothing', max_length=1500),
        ),
    ]
