# Generated by Django 5.2.5 on 2025-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Items',
            field=models.CharField(default='nothing', max_length=1501),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='password',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(default='nothing', max_length=101),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=401),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=201),
        ),
    ]
