# Generated by Django 5.2.5 on 2025-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orders_items_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Items',
            field=models.CharField(default='nothing', max_length=1500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='password',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
